import { randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import fs from "node:fs";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import postgres from "postgres";
import { applyPendingMigrations, ensurePostgresDatabase } from "./client.js";
import { prepareEmbeddedPostgresNativeRuntime } from "./embedded-postgres-native.js";

type EmbeddedPostgresInstance = {
  initialise(): Promise<void>;
  start(): Promise<void>;
  stop(): Promise<void>;
};

type EmbeddedPostgresCtor = new (opts: {
  databaseDir: string;
  user: string;
  password: string;
  port: number;
  persistent: boolean;
  initdbFlags?: string[];
  onLog?: (message: unknown) => void;
  onError?: (message: unknown) => void;
}) => EmbeddedPostgresInstance;

export type EmbeddedPostgresTestSupport = {
  supported: boolean;
  reason?: string;
};

export type EmbeddedPostgresTestDatabase = {
  connectionString: string;
  cleanup(): Promise<void>;
};

let embeddedPostgresSupportPromise: Promise<EmbeddedPostgresTestSupport> | null = null;

const DEFAULT_PAPERCLIP_EMBEDDED_POSTGRES_PORT = 54329;
const DEFAULT_EMBEDDED_POSTGRES_STARTUP_TIMEOUT_MS = 10_000;
const DEFAULT_EMBEDDED_POSTGRES_STOP_TIMEOUT_MS = 2_000;
const EXTERNAL_TEST_DATABASE_HOST = "127.0.0.1";
const EXTERNAL_TEST_DATABASE_PORT = "5432";
const EXTERNAL_TEST_DATABASE_NAME = "paperclip_test";
const EXTERNAL_TEST_DATABASE_USER = "paperclip";
const EXTERNAL_TEST_DATABASE_DATA_DIRECTORY = "/var/lib/postgresql/data";
const EXTERNAL_TEST_DATABASE_MAX_POSTMASTER_AGE_SECONDS = 20 * 60;
const EXTERNAL_TEST_DATABASE_ADVISORY_LOCK_KEY = 1_279_004_016;
const EXTERNAL_TEST_DATABASE_AUDIT_PREFIX = "[paperclip-test-db-exception]";
const GENERATED_EXTERNAL_TEST_DATABASE_NAME = /^paperclip_test_[a-f0-9]{32}$/;
const execFileAsync = promisify(execFile);

function getExternalTestDatabaseUrl(): string | null {
  return process.env.PAPERCLIP_TEST_DATABASE_URL?.trim() || null;
}

function normalizeDatabaseHostname(hostname: string): string {
  return hostname.toLowerCase().replace(/^\[|\]$/g, "");
}

export function validateExternalTestDatabaseUrl(rawUrl: string): URL {
  let parsed: URL;
  try {
    parsed = new URL(rawUrl);
  } catch {
    throw new Error("PAPERCLIP_TEST_DATABASE_URL must be a valid PostgreSQL URL");
  }
  if (parsed.protocol !== "postgres:" && parsed.protocol !== "postgresql:") {
    throw new Error("PAPERCLIP_TEST_DATABASE_URL must use the postgres or postgresql protocol");
  }
  const hostname = normalizeDatabaseHostname(parsed.hostname);
  if (hostname !== EXTERNAL_TEST_DATABASE_HOST) {
    throw new Error(
      `PAPERCLIP_TEST_DATABASE_URL must use ${EXTERNAL_TEST_DATABASE_HOST}; ` +
      "refusing any configurable or remote destination",
    );
  }
  if (parsed.port !== EXTERNAL_TEST_DATABASE_PORT) {
    throw new Error(
      `PAPERCLIP_TEST_DATABASE_URL must use the dedicated CI service port ${EXTERNAL_TEST_DATABASE_PORT}`,
    );
  }
  let databaseName: string;
  let username: string;
  try {
    databaseName = decodeURIComponent(parsed.pathname.replace(/^\//, ""));
    username = decodeURIComponent(parsed.username);
  } catch {
    throw new Error("PAPERCLIP_TEST_DATABASE_URL contains invalid percent encoding");
  }
  if (databaseName !== EXTERNAL_TEST_DATABASE_NAME) {
    throw new Error(
      `PAPERCLIP_TEST_DATABASE_URL must name the dedicated ${EXTERNAL_TEST_DATABASE_NAME} control database`,
    );
  }
  if (username !== EXTERNAL_TEST_DATABASE_USER || parsed.password.length === 0) {
    throw new Error(
      `PAPERCLIP_TEST_DATABASE_URL must authenticate as the dedicated ${EXTERNAL_TEST_DATABASE_USER} CI role`,
    );
  }
  if (parsed.search || parsed.hash) {
    throw new Error("PAPERCLIP_TEST_DATABASE_URL must not contain connection options or fragments");
  }
  return parsed;
}

export type ExternalTestDatabaseRuntimeEvidence = {
  currentDatabase: string;
  currentUser: string;
  serverVersionNum: number;
  dataDirectory: string;
  postmasterAgeSeconds: number;
  inRecovery: boolean;
  userDatabaseNames: string[];
  loginRoleNames: string[];
  userRelationCount: number;
};

export function validateExternalTestDatabaseHostedRuntime(
  env: NodeJS.ProcessEnv = process.env,
): void {
  if (
    env.GITHUB_ACTIONS !== "true" ||
    env.RUNNER_ENVIRONMENT !== "github-hosted" ||
    env.GITHUB_SERVER_URL !== "https://github.com"
  ) {
    throw new Error(
      "External PostgreSQL test mode requires GitHub's non-overridable github-hosted runtime attestation",
    );
  }
}

export function validateExternalTestDatabaseRuntimeEvidence(
  evidence: ExternalTestDatabaseRuntimeEvidence,
  expectedLeaseDatabaseName: string | null,
): void {
  if (expectedLeaseDatabaseName && !GENERATED_EXTERNAL_TEST_DATABASE_NAME.test(expectedLeaseDatabaseName)) {
    throw new Error("External PostgreSQL test lease name was not generated by the test harness");
  }

  const expectedDatabaseNames = [
    EXTERNAL_TEST_DATABASE_NAME,
    "postgres",
    ...(expectedLeaseDatabaseName ? [expectedLeaseDatabaseName] : []),
  ].sort();
  const actualDatabaseNames = [...evidence.userDatabaseNames].sort();
  const actualRoleNames = [...evidence.loginRoleNames].sort();

  const disposable =
    evidence.currentDatabase === EXTERNAL_TEST_DATABASE_NAME &&
    evidence.currentUser === EXTERNAL_TEST_DATABASE_USER &&
    evidence.serverVersionNum >= 160_000 &&
    evidence.serverVersionNum < 170_000 &&
    evidence.dataDirectory === EXTERNAL_TEST_DATABASE_DATA_DIRECTORY &&
    Number.isFinite(evidence.postmasterAgeSeconds) &&
    evidence.postmasterAgeSeconds >= 0 &&
    evidence.postmasterAgeSeconds <= EXTERNAL_TEST_DATABASE_MAX_POSTMASTER_AGE_SECONDS &&
    evidence.inRecovery === false &&
    JSON.stringify(actualDatabaseNames) === JSON.stringify(expectedDatabaseNames) &&
    JSON.stringify(actualRoleNames) === JSON.stringify([EXTERNAL_TEST_DATABASE_USER]) &&
    evidence.userRelationCount === 0;

  if (!disposable) {
    throw new Error(
      "External PostgreSQL runtime did not match the fail-closed disposable postgres:16 service profile",
    );
  }
}

type ExternalTestDatabaseMutationAction = "create" | "migrate" | "drop";

export function formatExternalTestDatabaseMutationAudit(input: {
  action: ExternalTestDatabaseMutationAction;
  targetDatabaseName: string;
}): string {
  if (!GENERATED_EXTERNAL_TEST_DATABASE_NAME.test(input.targetDatabaseName)) {
    throw new Error("External PostgreSQL audit target was not generated by the test harness");
  }
  return (
    `${EXTERNAL_TEST_DATABASE_AUDIT_PREFIX} action=${input.action} ` +
    `endpoint=${EXTERNAL_TEST_DATABASE_HOST}:${EXTERNAL_TEST_DATABASE_PORT} ` +
    `controlDatabase=${EXTERNAL_TEST_DATABASE_NAME} targetDatabase=${input.targetDatabaseName} ` +
    "attestation=github-hosted+postgres16-disposable"
  );
}

function quoteDatabaseIdentifier(value: string): string {
  if (!/^[a-z_][a-z0-9_]*$/.test(value)) throw new Error("Unsafe generated test database name");
  return `"${value}"`;
}

function databaseUrl(base: URL, databaseName: string): string {
  const result = new URL(base.toString());
  result.pathname = `/${databaseName}`;
  return result.toString();
}

type ExternalTestDatabaseAdminSql = ReturnType<typeof postgres>;

async function readExternalTestDatabaseRuntimeEvidence(
  sql: ExternalTestDatabaseAdminSql,
): Promise<ExternalTestDatabaseRuntimeEvidence> {
  const identityRows = await sql<{
    currentDatabase: string;
    currentUser: string;
    serverVersionNum: number;
    dataDirectory: string;
    postmasterAgeSeconds: number;
    inRecovery: boolean;
  }[]>`
    SELECT
      current_database() AS "currentDatabase",
      current_user AS "currentUser",
      current_setting('server_version_num')::integer AS "serverVersionNum",
      current_setting('data_directory') AS "dataDirectory",
      EXTRACT(EPOCH FROM (clock_timestamp() - pg_postmaster_start_time()))::double precision
        AS "postmasterAgeSeconds",
      pg_is_in_recovery() AS "inRecovery"
  `;
  const databaseRows = await sql<{ name: string }[]>`
    SELECT datname AS name
    FROM pg_database
    WHERE NOT datistemplate
    ORDER BY datname
  `;
  const roleRows = await sql<{ name: string }[]>`
    SELECT rolname AS name
    FROM pg_roles
    WHERE rolcanlogin AND rolname !~ '^pg_'
    ORDER BY rolname
  `;
  const relationRows = await sql<{ count: number }[]>`
    SELECT COUNT(*)::integer AS count
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname <> 'information_schema'
      AND n.nspname !~ '^pg_'
  `;
  const identity = identityRows[0];
  if (!identity) {
    throw new Error("External PostgreSQL runtime attestation returned no identity row");
  }
  return {
    ...identity,
    userDatabaseNames: databaseRows.map((row) => row.name),
    loginRoleNames: roleRows.map((row) => row.name),
    userRelationCount: relationRows[0]?.count ?? -1,
  };
}

async function attestExternalTestDatabaseRuntime(
  sql: ExternalTestDatabaseAdminSql,
  expectedLeaseDatabaseName: string | null,
): Promise<void> {
  validateExternalTestDatabaseHostedRuntime();
  const evidence = await readExternalTestDatabaseRuntimeEvidence(sql);
  validateExternalTestDatabaseRuntimeEvidence(evidence, expectedLeaseDatabaseName);
}

async function runAuditedExternalTestDatabaseMutation<T>(input: {
  sql: ExternalTestDatabaseAdminSql;
  action: ExternalTestDatabaseMutationAction;
  targetDatabaseName: string;
  expectedLeaseDatabaseName: string | null;
  mutate: () => Promise<T>;
}): Promise<T> {
  await attestExternalTestDatabaseRuntime(input.sql, input.expectedLeaseDatabaseName);
  console.warn(formatExternalTestDatabaseMutationAudit(input));
  return input.mutate();
}

async function dropExternalTestDatabase(
  sql: ExternalTestDatabaseAdminSql,
  databaseName: string,
): Promise<void> {
  await runAuditedExternalTestDatabaseMutation({
    sql,
    action: "drop",
    targetDatabaseName: databaseName,
    expectedLeaseDatabaseName: databaseName,
    mutate: async () => {
      const quotedDatabaseName = quoteDatabaseIdentifier(databaseName);
      await sql.unsafe(`DROP DATABASE IF EXISTS ${quotedDatabaseName} WITH (FORCE)`);
    },
  });
  const remaining = await sql<{ exists: boolean }[]>`
    SELECT EXISTS(SELECT 1 FROM pg_database WHERE datname = ${databaseName}) AS exists
  `;
  if (remaining[0]?.exists) {
    throw new Error("External PostgreSQL test database cleanup could not be verified");
  }
}

async function startExternalPostgresTestDatabase(rawUrl: string): Promise<EmbeddedPostgresTestDatabase> {
  const baseUrl = validateExternalTestDatabaseUrl(rawUrl);
  const databaseName = `paperclip_test_${randomUUID().replaceAll("-", "")}`;
  const adminUrl = baseUrl.toString();
  const sql = postgres(adminUrl, { max: 1, onnotice: () => {} });
  try {
    await sql`SELECT pg_advisory_lock(${EXTERNAL_TEST_DATABASE_ADVISORY_LOCK_KEY})`;
    await runAuditedExternalTestDatabaseMutation({
      sql,
      action: "create",
      targetDatabaseName: databaseName,
      expectedLeaseDatabaseName: null,
      mutate: async () => {
        await sql.unsafe(`CREATE DATABASE ${quoteDatabaseIdentifier(databaseName)}`);
      },
    });

    const connectionString = databaseUrl(baseUrl, databaseName);
    try {
      await runAuditedExternalTestDatabaseMutation({
        sql,
        action: "migrate",
        targetDatabaseName: databaseName,
        expectedLeaseDatabaseName: databaseName,
        mutate: () => applyPendingMigrations(connectionString),
      });
    } catch (error) {
      try {
        await dropExternalTestDatabase(sql, databaseName);
      } catch (cleanupError) {
        throw new AggregateError(
          [error, cleanupError],
          "External PostgreSQL test database migration failed and cleanup could not be verified",
        );
      }
      throw error;
    }

    let cleaned = false;
    return {
      connectionString,
      cleanup: async () => {
        if (cleaned) return;
        await dropExternalTestDatabase(sql, databaseName);
        await sql.end();
        cleaned = true;
      },
    };
  } catch (error) {
    await sql.end().catch(() => undefined);
    throw error;
  }
}

function getReservedTestPorts(): Set<number> {
  const configuredPorts = [
    DEFAULT_PAPERCLIP_EMBEDDED_POSTGRES_PORT,
    Number.parseInt(process.env.PAPERCLIP_EMBEDDED_POSTGRES_PORT ?? "", 10),
    ...String(process.env.PAPERCLIP_TEST_POSTGRES_RESERVED_PORTS ?? "")
      .split(",")
      .map((value) => Number.parseInt(value.trim(), 10)),
  ];
  return new Set(configuredPorts.filter((port) => Number.isInteger(port) && port > 0 && port <= 65535));
}

async function getEmbeddedPostgresCtor(): Promise<EmbeddedPostgresCtor> {
  const mod = await import("embedded-postgres");
  await prepareEmbeddedPostgresNativeRuntime();
  return mod.default as EmbeddedPostgresCtor;
}

async function getAvailablePort(): Promise<number> {
  const reservedPorts = getReservedTestPorts();
  for (let attempt = 0; attempt < 20; attempt += 1) {
    const port = await new Promise<number>((resolve, reject) => {
      const server = net.createServer();
      server.unref();
      server.on("error", reject);
      server.listen(0, "127.0.0.1", () => {
        const address = server.address();
        if (!address || typeof address === "string") {
          server.close(() => reject(new Error("Failed to allocate test port")));
          return;
        }
        const { port } = address;
        server.close((error) => {
          if (error) reject(error);
          else resolve(port);
        });
      });
    });

    if (!reservedPorts.has(port)) return port;
  }

  throw new Error(
    `Failed to allocate embedded Postgres test port outside reserved Paperclip ports: ${[
      ...reservedPorts,
    ].join(", ")}`,
  );
}

async function createEmbeddedPostgresTestInstance(tempDirPrefix: string) {
  const port = await getAvailablePort();
  const EmbeddedPostgres = await getEmbeddedPostgresCtor();
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), tempDirPrefix));
  try {
    const instance = new EmbeddedPostgres({
      databaseDir: dataDir,
      user: "paperclip",
      password: "paperclip",
      port,
      persistent: true,
      initdbFlags: ["--encoding=UTF8", "--locale=C", "--lc-messages=C"],
      onLog: () => {},
      onError: () => {},
    });

    return { dataDir, port, instance };
  } catch (error) {
    cleanupEmbeddedPostgresTestDirs(dataDir);
    throw error;
  }
}

function cleanupEmbeddedPostgresTestDirs(dataDir: string) {
  fs.rmSync(dataDir, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
}

async function terminateEmbeddedPostgresProcessesForDataDir(dataDir: string): Promise<void> {
  if (process.platform === "win32") {
    const script = [
      "$target = $env:PAPERCLIP_TEST_POSTGRES_DATA_DIR",
      "Get-CimInstance Win32_Process | Where-Object {",
      "  $processName = [string]$_.Name",
      "  $commandLine = [string]$_.CommandLine",
      "  ($processName -ieq \"initdb.exe\" -or $processName -ieq \"postgres.exe\") -and",
      "    $commandLine.Contains($target)",
      "} | ForEach-Object {",
      "  & taskkill.exe /PID ([string]$_.ProcessId) /T /F | Out-Null",
      "}",
    ].join("\n");
    await execFileAsync("powershell.exe", ["-NoProfile", "-NonInteractive", "-Command", script], {
      env: { ...process.env, PAPERCLIP_TEST_POSTGRES_DATA_DIR: dataDir },
      timeout: 5_000,
      windowsHide: true,
    });
    return;
  }

  const { stdout } = await execFileAsync("ps", ["-eo", "pid=,args="], { timeout: 5_000 });
  for (const line of stdout.split(/\r?\n/)) {
    const match = line.trim().match(/^(\d+)\s+(.*)$/);
    if (!match) continue;
    const pid = Number.parseInt(match[1]!, 10);
    const commandLine = match[2]!;
    if (
      pid !== process.pid &&
      (commandLine.includes(`--pgdata=${dataDir}`) || commandLine.includes(`-D ${dataDir}`))
    ) {
      try {
        process.kill(pid, "SIGKILL");
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ESRCH") throw error;
      }
    }
  }
}

async function removeEmbeddedPostgresTestDir(dataDir: string): Promise<void> {
  try {
    cleanupEmbeddedPostgresTestDirs(dataDir);
  } catch (initialCleanupError) {
    let terminationError: unknown;
    try {
      await terminateEmbeddedPostgresProcessesForDataDir(dataDir);
    } catch (error) {
      terminationError = error;
    }

    try {
      cleanupEmbeddedPostgresTestDirs(dataDir);
    } catch (retryCleanupError) {
      throw new AggregateError(
        [initialCleanupError, terminationError, retryCleanupError].filter(Boolean),
        "Embedded PostgreSQL test data directory cleanup failed after terminating its processes",
      );
    }
  }
}

function formatEmbeddedPostgresError(error: unknown): string {
  if (error instanceof Error && error.message.length > 0) return error.message;
  if (typeof error === "string" && error.length > 0) return error;
  return "embedded Postgres startup failed";
}

function getEmbeddedPostgresStartupTimeoutMs(): number {
  const configured = Number.parseInt(
    process.env.PAPERCLIP_EMBEDDED_POSTGRES_STARTUP_TIMEOUT_MS ?? "",
    10,
  );
  return Number.isInteger(configured) && configured > 0
    ? configured
    : DEFAULT_EMBEDDED_POSTGRES_STARTUP_TIMEOUT_MS;
}

async function runEmbeddedPostgresOperationWithTimeout<T>(
  operation: () => Promise<T>,
  phase: string,
  timeoutMs: number,
): Promise<T> {
  let timeout: NodeJS.Timeout | undefined;
  try {
    return await Promise.race([
      Promise.resolve().then(operation),
      new Promise<never>((_resolve, reject) => {
        timeout = setTimeout(() => {
          reject(new Error(`Embedded PostgreSQL ${phase} timed out after ${timeoutMs}ms`));
        }, timeoutMs);
        timeout.unref();
      }),
    ]);
  } finally {
    if (timeout) clearTimeout(timeout);
  }
}

async function startEmbeddedPostgresInstance(
  instance: EmbeddedPostgresInstance,
  timeoutMs: number,
): Promise<void> {
  await runEmbeddedPostgresOperationWithTimeout(
    () => instance.initialise(),
    "initialise",
    timeoutMs,
  );
  await runEmbeddedPostgresOperationWithTimeout(() => instance.start(), "start", timeoutMs);
}

async function cleanupEmbeddedPostgresTestInstance(
  instance: EmbeddedPostgresInstance | null,
  dataDir: string | null,
  startupTimeoutMs: number,
): Promise<void> {
  try {
    if (instance) {
      await runEmbeddedPostgresOperationWithTimeout(
        () => instance.stop(),
        "stop",
        Math.min(startupTimeoutMs, DEFAULT_EMBEDDED_POSTGRES_STOP_TIMEOUT_MS),
      ).catch(() => {});
    }
  } finally {
    if (dataDir) await removeEmbeddedPostgresTestDir(dataDir);
  }
}

async function probeEmbeddedPostgresSupport(): Promise<EmbeddedPostgresTestSupport> {
  let dataDir: string | null = null;
  let instance: EmbeddedPostgresInstance | null = null;
  const startupTimeoutMs = getEmbeddedPostgresStartupTimeoutMs();

  try {
    const created = await createEmbeddedPostgresTestInstance(
      "paperclip-embedded-postgres-probe-",
    );
    dataDir = created.dataDir;
    instance = created.instance;
    await startEmbeddedPostgresInstance(instance, startupTimeoutMs);
    return { supported: true };
  } catch (error) {
    return {
      supported: false,
      reason: formatEmbeddedPostgresError(error),
    };
  } finally {
    await cleanupEmbeddedPostgresTestInstance(instance, dataDir, startupTimeoutMs);
  }
}

export async function getEmbeddedPostgresTestSupport(): Promise<EmbeddedPostgresTestSupport> {
  const externalTestDatabaseUrl = getExternalTestDatabaseUrl();
  if (externalTestDatabaseUrl) {
    const baseUrl = validateExternalTestDatabaseUrl(externalTestDatabaseUrl);
    validateExternalTestDatabaseHostedRuntime();
    const sql = postgres(baseUrl.toString(), { max: 1, onnotice: () => {} });
    try {
      await attestExternalTestDatabaseRuntime(sql, null);
      return { supported: true };
    } finally {
      await sql.end();
    }
  }
  if (!embeddedPostgresSupportPromise) {
    embeddedPostgresSupportPromise = probeEmbeddedPostgresSupport();
  }
  return await embeddedPostgresSupportPromise;
}

export async function startEmbeddedPostgresTestDatabase(
  tempDirPrefix: string,
): Promise<EmbeddedPostgresTestDatabase> {
  const externalTestDatabaseUrl = getExternalTestDatabaseUrl();
  if (externalTestDatabaseUrl) {
    return startExternalPostgresTestDatabase(externalTestDatabaseUrl);
  }

  let dataDir: string | null = null;
  let instance: EmbeddedPostgresInstance | null = null;
  const startupTimeoutMs = getEmbeddedPostgresStartupTimeoutMs();

  try {
    const created = await createEmbeddedPostgresTestInstance(tempDirPrefix);
    dataDir = created.dataDir;
    instance = created.instance;
    const { port } = created;
    await startEmbeddedPostgresInstance(instance, startupTimeoutMs);

    const adminConnectionString = `postgres://paperclip:paperclip@127.0.0.1:${port}/postgres`;
    await ensurePostgresDatabase(adminConnectionString, "paperclip");
    const connectionString = `postgres://paperclip:paperclip@127.0.0.1:${port}/paperclip`;
    await applyPendingMigrations(connectionString);

    let cleaned = false;
    return {
      connectionString,
      cleanup: async () => {
        if (cleaned) return;
        await cleanupEmbeddedPostgresTestInstance(instance, dataDir, startupTimeoutMs);
        cleaned = true;
      },
    };
  } catch (error) {
    await cleanupEmbeddedPostgresTestInstance(instance, dataDir, startupTimeoutMs);
    throw new Error(
      `Failed to start embedded PostgreSQL test database: ${formatEmbeddedPostgresError(error)}`,
    );
  }
}
